services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: credrails_assessment
    container_name: reconciliation
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - '8000:8000'
    volumes:
      - .:/app
      - db_data:/db.sqlite3
    environment:
      - DEBUG=1
    develop:
      watch:
        - action: sync+restart
          path: ./
          target: /app
          ignore:
            - db.sqlite3
        - action: rebuild
          path: requirements.txt

volumes:
  db_data:
